name: gitesprit
services:
  postgres:
    container_name: postgres-sql-gitesprit
    image: postgres:17-alpine
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      PGDATA: /var/lib/postgresql/data
      POSTGRES_DB: gitesprit
    volumes:
      - postgres:/var/lib/postgresql/data
    #      - ./init-scripts:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    networks:
      - gitesprit-network
    restart: unless-stopped
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U username" ]
      interval: 10s
      timeout: 5s
      retries: 5
  keycloak:
    container_name: keycloak-gitesprit
    image: quay.io/keycloak/keycloak:26.2
    ports:
      - "8085:8080" #  web interface
      - "9000:9000" #  health check
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
      KC_HTTP_ENABLED: true
      KC_HEALTH_ENABLED: true
      KC_METRICS_ENABLED: true
      AGR_BACKEND_BASE_URL: "http://host.docker.internal:8081"
    networks:
      - gitesprit-network
    volumes:
#      - ../kc-providers:/opt/keycloak/providers/
      - ../kc-realm/:/opt/keycloak/data/import/
    depends_on:
      - postgres
    command:
      - start-dev
      - --import-realm
  mail-dev:
    container_name: mail-dev-gitesprit
    image: maildev/maildev
    ports:
      - "1080:1080"
      - "1025:1025"
    networks:
      - gitesprit-network

networks:
  gitesprit-network:
    driver: bridge

volumes:
  postgres:
    driver: local